### ISSUE TITLE
Ability to set a password value

### ISSUE THREAD

**Issue by jaydeland** [JamesTheHacker/passman#1]
As a user I would like the ability to set the password value with a new mode called set, so I can populate passman with existing passwords.

**Comment by JamesTheHacker** [comment]
Will get this added at some point today.

**Comment by JamesTheHacker** [comment]
https://github.com/JamesTheHacker/passman/pull/2

**Comment by JamesTheHacker** [comment]
#2 

Could you test this branch. If everything works fine I will merge.
